In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Churn_Modelling_with_nulls.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602.0,Hargrave,619.0,France,Female,NaN,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,2,15647311.0,Hill,608.0,Spain,Female,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,3,15619304.0,Onio,502.0,France,Female,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,4,15701354.0,Boni,699.0,France,Female,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,5,15737888.0,Mitchell,850.0,Spain,Female,43.0,NaN,125510.82,1.0,1.0,1.0,79084.10,0.0

In [3]:
df.shape

(10000, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       9505 non-null   float64
 2   Surname          9467 non-null   object
 3   CreditScore      9484 non-null   float64
 4   Geography        9498 non-null   object
 5   Gender           9519 non-null   object
 6   Age              9481 non-null   float64
 7   Tenure           9486 non-null   float64
 8   Balance          9503 non-null   float64
 9   NumOfProducts    9514 non-null   float64
 10  HasCrCard        9503 non-null   float64
 11  IsActiveMember   9503 non-null   float64
 12  EstimatedSalary  9519 non-null   float64
 13  Exited           9522 non-null   float64
dtypes: float64(10), int64(1), object(3)
memory usage: 1.1+ MB

In [5]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,9.505000e+03,9484.000000,9481.000000,9486.000000,9503.000000,9514.000000,9503.000000,9503.000000,9519.000000,9522.000000
mean,5000.50000,1.569096e+07,650.677562,38.928910,5.010120,76339.509882,1.530902,0.704199,0.513206,100143.227946,0.202373
std,2886.89568,7.199815e+04,96.530690,10.487475,2.888164,62410.870288,0.581199,0.456426,0.499852,57593.023485,0.401790
min,1.00000,1.556571e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.580000,0.000000
25%,2500.75000,1.562856e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.000000,0.000000,50903.280000,0.000000
50%,5000.50000,1.569067e+07,652.000000,37.000000,5.000000,97042.600000,1.000000,1.000000,1.000000,100187.430000,0.000000
75%,7500.25000,1.575334e+07,718.000000,44.000000,7.000000,127714.790000,2.000000,1.000000,1.000000,149464.930000,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.000000,1.000000,199992.480000,1.000000

In [6]:
df.isnull().sum()

RowNumber            0
CustomerId         495
Surname            533
CreditScore        516
Geography          502
Gender             481
Age                519
Tenure             514
Balance            497
NumOfProducts      486
HasCrCard          497
IsActiveMember     497
EstimatedSalary    481
Exited             478
dtype: int64

# Numerical columns

In [7]:
num_cols = df.select_dtypes(include=['int64','float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical Columns

In [8]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [9]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [10]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [11]:
df.to_csv("cleaned_churn_data.csv", index=False)